### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [AdrienneSturgeon/Dasmotos#4]
Overall, this project was one of the better written projects that I've seen and it shows through the flawless replication from the design spec.
I'm very interested in seeing your upcoming projects to see how well you can maintain it's organization and cleanliness.

Grade: Exceeds expectation, wonderful work!

**Comment by AdrienneSturgeon** [comment]
Thank You! There were a couple tricky parts but I'm glad it all turned out well.
